### ISSUE TITLE
[Operate/Tasklist] Elasticsearch 8 support 

### ISSUE THREAD

**Issue by ralfpuchert** [camunda/camunda-platform-docs#1844]
## Description
There a 2 features which enabled the support of Elasticsearch 8 

1. Operate and Tasklist supports Elasticsearch 8 cluster by using compatibility mode.
2. ILM can be used to replace curator.

### Compatibility mode
The compatibility mode is enabled in order to communicate with Elasticsearch 8.2+
It is tested until 8.6. 

### Index Lifecycle Management
In order to replace the curator ILM can be defined for archived indices.
ILM is disabled by default. The min age for deleting archived indices is 30 days.

Configuration part in `application.yml`:
```yaml
camunda.operate:
  archiver:
    waitPeriodBeforeArchiving: 5m
    ilmEnabled: true
    ilmMinAgeForDeleteArchivedIndices: 10m
```
